import type { Map as MapboxMap } from "mapbox-gl";

/**
 * Sonar coverage polygon layer.
 *
 * Renders the actual scan coverage footprints derived from WMS imagery
 * as semi-transparent fill polygons. Generated by scripts/extract_sonar_coverage.py
 * from AusSeabed WMS data (CC BY 4.0, Governments of Australia, Malaysia and PRC).
 */

interface CoverageSource {
  id: string;
  label: string;
  file: string;
  fillColor: string;
  fillOpacity: number;
}

const COVERAGE_SOURCES: CoverageSource[] = [
  { id: "auv", label: "AUV Side Scan", file: "auv_coverage.geojson", fillColor: "#FF8C00", fillOpacity: 0.3 },
  { id: "deeptow", label: "Deep Tow", file: "deeptow_coverage.geojson", fillColor: "#FFB300", fillOpacity: 0.3 },
  {
    id: "gophoenix",
    label: "Go Phoenix SAS",
    file: "gophoenix_coverage.geojson",
    fillColor: "#FFD600",
    fillOpacity: 0.3,
  },
  {
    id: "bathymetry",
    label: "Bathymetry",
    file: "bathymetry_coverage.geojson",
    fillColor: "#78909C",
    fillOpacity: 0.2,
  },
];

export { COVERAGE_SOURCES };

export async function loadSonarCoverageLayer(map: MapboxMap): Promise<void> {
  for (const source of COVERAGE_SOURCES) {
    const sourceId = `sonar-coverage-${source.id}-source`;
    const fillId = `sonar-coverage-${source.id}-fill`;
    const outlineId = `sonar-coverage-${source.id}-outline`;

    let geojson: GeoJSON.FeatureCollection;
    try {
      const res = await fetch(`./data/sonar_coverage/${source.file}`);
      if (!res.ok) continue;
      geojson = await res.json();
    } catch {
      continue;
    }

    map.addSource(sourceId, { type: "geojson", data: geojson });

    map.addLayer({
      id: fillId,
      type: "fill",
      source: sourceId,
      paint: {
        "fill-color": source.fillColor,
        "fill-opacity": source.fillOpacity,
      },
      layout: { visibility: "none" },
    });

    map.addLayer({
      id: outlineId,
      type: "line",
      source: sourceId,
      paint: {
        "line-color": source.fillColor,
        "line-opacity": 0.8,
        "line-width": 1,
      },
      layout: { visibility: "none" },
    });
  }
}

export function setSonarCoverageVisible(map: MapboxMap, id: string, visible: boolean): void {
  const visibility = visible ? "visible" : "none";
  const fillId = `sonar-coverage-${id}-fill`;
  const outlineId = `sonar-coverage-${id}-outline`;
  if (map.getLayer(fillId)) map.setLayoutProperty(fillId, "visibility", visibility);
  if (map.getLayer(outlineId)) map.setLayoutProperty(outlineId, "visibility", visibility);
}
