use serde::Serialize;

#[derive(Debug, Clone, Serialize)]
pub struct Anomaly {
    pub id: String,
    pub category: String,
    pub lat: Option<f64>,
    pub lon: Option<f64>,
    pub title: String,
    pub date: String,
    pub confidence: String,
    pub summary: String,
    pub detail: String,
    pub source: String,
    pub source_url: Option<String>,
    pub implication: String,
    pub status: String,
    pub conflicts_with: Vec<String>,
    pub supports: Vec<String>,
}

pub fn get_anomalies() -> Vec<Anomaly> {
    vec![
        Anomaly {
            id: "java_anomaly".to_string(),
            category: "acoustic".to_string(),
            lat: Some(-8.36),
            lon: Some(107.92),
            title: "Java Anomaly — Uncataloged Hydroacoustic Event".to_string(),
            date: "2014-03-08T01:15:18Z".to_string(),
            confidence: "medium".to_string(),
            summary: "A strong acoustic event detected at the Diego Garcia H08 hydrophone array from the direction of Java, stronger than nearby cataloged quakes and never formally resolved.".to_string(),
            detail: "Triangulated origin was reported at 8.36S 107.92E directly on the 7th arc, with timing roughly 55 minutes after expected impact. If genuine, it is more consistent with an underwater implosion or later sinking event than immediate impact.".to_string(),
            source: "370location.org — Ed Anderson".to_string(),
            source_url: None,
            implication: "Would place the crash site near Java and far north of the searched southern Indian Ocean corridors.".to_string(),
            status: "unexplored".to_string(),
            conflicts_with: vec![],
            supports: vec!["thermal_plume_aqua_modis".to_string()],
        },
        Anomaly {
            id: "barnacle_large_specimens".to_string(),
            category: "biological".to_string(),
            lat: Some(-20.9),
            lon: Some(55.5),
            title: "Largest Barnacles on Flaperon — Withheld from Analysis".to_string(),
            date: "2015-07-29".to_string(),
            confidence: "high".to_string(),
            summary: "The largest flaperon barnacles may preserve the earliest temperature history after impact, but they have not been released for independent analysis.".to_string(),
            detail: "Published isotope work on smaller specimens points to warm-water drift histories. If the largest and likely earliest-attached specimens were analyzed, they could narrow the origin corridor substantially.".to_string(),
            source: "Al-Qattan et al. (2023), AGU Advances".to_string(),
            source_url: Some("https://doi.org/10.1029/2023AV000915".to_string()),
            implication: "A warm-water origin would sit uneasily with the colder far-south search assumption.".to_string(),
            status: "unexplored".to_string(),
            conflicts_with: vec![],
            supports: vec![],
        },
        Anomaly {
            id: "thermal_plume_aqua_modis".to_string(),
            category: "satellite_image".to_string(),
            lat: Some(-39.47),
            lon: Some(90.45),
            title: "Hydrocarbon Plume — NASA MODIS Thermal Imagery".to_string(),
            date: "2014-03-08T04:46:30Z".to_string(),
            confidence: "low".to_string(),
            summary: "An isolated dark cloud feature in MODIS thermal imagery was interpreted as a possible hydrocarbon plume a few hours after expected impact.".to_string(),
            detail: "A second weaker detection was claimed in a later pass, with the motion attributed to high-altitude winds. The interpretation is speculative but geographically overlaps the southern end of the ATSB corridor.".to_string(),
            source: "370location.org independent analysis".to_string(),
            source_url: None,
            implication: "If real, it supports a southern origin near the lower ATSB search band.".to_string(),
            status: "unexplored".to_string(),
            conflicts_with: vec!["barnacle_large_specimens".to_string()],
            supports: vec![],
        },
        Anomaly {
            id: "sdu_temperature_fingerprint".to_string(),
            category: "signal".to_string(),
            lat: None,
            lon: None,
            title: "SDU Oscillator Cold-Start Temperature — Untested".to_string(),
            date: "2014-03-08T18:25:27Z".to_string(),
            confidence: "medium".to_string(),
            summary: "The 18:25 reboot warm-up curve may encode SDU starting temperature, but no public manufacturer test has been released.".to_string(),
            detail: "A cold-soaked SDU after depressurization would likely show a different warm-up signature than a normal warm reboot. That could constrain both depressurization and BFO bias assumptions.".to_string(),
            source: "Independent Group discussions".to_string(),
            source_url: None,
            implication: "Could change interpretation of the 18:25 event and narrow the set of compatible physical scenarios.".to_string(),
            status: "unexplored".to_string(),
            conflicts_with: vec![],
            supports: vec![],
        },
        Anomaly {
            id: "rx_power_dropoff".to_string(),
            category: "signal".to_string(),
            lat: None,
            lon: None,
            title: "Rx Power & C/No Drop During Phone Calls".to_string(),
            date: "2014-03-07T23:14:00Z".to_string(),
            confidence: "medium".to_string(),
            summary: "The unanswered phone calls show falling receive power and worsening carrier-to-noise without the same kind of BFO shift, which has never been adequately modeled.".to_string(),
            detail: "Potential explanations include banking, changing antenna geometry, or descent. Each would imply a different state of aircraft control near arc 6.".to_string(),
            source: "Inmarsat Signalling Unit Log".to_string(),
            source_url: None,
            implication: "Could constrain aircraft attitude and active piloting late in the flight.".to_string(),
            status: "unexplored".to_string(),
            conflicts_with: vec![],
            supports: vec![],
        },
        Anomaly {
            id: "cloud_trail_modis".to_string(),
            category: "satellite_image".to_string(),
            lat: Some(-33.0),
            lon: Some(100.0),
            title: "300km Cloud Trail Anomaly in MODIS Imagery".to_string(),
            date: "2014-03-08T03:07:00Z".to_string(),
            confidence: "low".to_string(),
            summary: "A long cloud anomaly visible across multiple MODIS images has been proposed as a wake-like trail from a late controlled flight path.".to_string(),
            detail: "The claim remains speculative, but the archive is public and well-suited to more systematic modern image analysis.".to_string(),
            source: "Lyne (2024), ResearchGate".to_string(),
            source_url: None,
            implication: "If real, it would suggest a controlled late path east of the main searched zones.".to_string(),
            status: "unexplored".to_string(),
            conflicts_with: vec![],
            supports: vec![],
        },
        Anomaly {
            id: "cocos_island_seismometer".to_string(),
            category: "acoustic".to_string(),
            lat: Some(-12.188),
            lon: Some(96.829),
            title: "Cocos Keeling Seismometer — Possible Flyby Signal".to_string(),
            date: "2014-03-08T00:50:00Z".to_string(),
            confidence: "medium".to_string(),
            summary: "A public Cocos Keeling seismometer anomaly has been interpreted as a possible aircraft flyby near the island.".to_string(),
            detail: "If the signal were confirmed as MH370, it would sharply constrain the route and strongly favor a much more northerly continuation than the official southern search.".to_string(),
            source: "370location.org — Ed Anderson".to_string(),
            source_url: None,
            implication: "Could anchor a specific waypoint route and rule out many southern arc 7 crossings.".to_string(),
            status: "unexplored".to_string(),
            conflicts_with: vec![],
            supports: vec!["java_anomaly".to_string()],
        },
    ]
}
