/// ERA5 monthly-mean 10m wind data for debris drift leeway.
///
/// Replaces the synthetic `wind_field_at()` climatology with real ERA5
/// reanalysis wind fields. Same spatial/temporal interpolation pattern as
/// the OSCAR surface current module.
///
/// Data source: ERA5 monthly averaged reanalysis on single levels.
/// DOI: 10.24381/cds.f17050d7
/// License: Copernicus License (free for research use with attribution).
///
/// Cache: JSON file at `src-tauri/.cache/era5_wind_monthly.json`,
/// generated by `knowledge/fetch_era5_wind.py`.
use std::fs;
use std::path::PathBuf;
use std::sync::OnceLock;

use serde::Deserialize;

const CACHE_VERSION: u32 = 1;

static CACHE: OnceLock<Option<Era5WindCache>> = OnceLock::new();

#[derive(Debug, Deserialize)]
struct Era5WindCache {
    version: u32,
    lats: Vec<f64>,
    lons: Vec<f64>,
    timesteps: Vec<Era5Timestep>,
}

#[derive(Debug, Deserialize)]
struct Era5Timestep {
    /// Days since 2014-03-08 (crash date)
    day_offset: f64,
    #[allow(dead_code)]
    date: String,
    /// Row-major [lat_index * lon_count + lon_index], east wind (m/s)
    u: Vec<f32>,
    /// Row-major, north wind (m/s)
    v: Vec<f32>,
}

/// Get interpolated ERA5 10m wind at a position and time.
///
/// Returns `(u_east, v_north)` in m/s, or `None` if the ERA5 cache is not
/// available or the position is outside the domain.
///
/// The returned wind is the raw 10m wind speed — the caller is responsible
/// for applying the leeway coefficient (typically 0.025 for the flaperon).
pub fn era5_wind_at(day_index: usize, lat: f64, lon: f64) -> Option<(f64, f64)> {
    let cache = CACHE.get_or_init(|| {
        load_cache()
            .map_err(|e| eprintln!("ERA5 wind: {e}"))
            .ok()
    });
    cache.as_ref()?.sample(day_index as f64, lat, lon)
}

/// Check whether the ERA5 wind cache is loaded and available.
pub fn era5_wind_available() -> bool {
    let cache = CACHE.get_or_init(|| {
        load_cache()
            .map_err(|e| eprintln!("ERA5 wind: {e}"))
            .ok()
    });
    cache.is_some()
}

impl Era5WindCache {
    fn sample(&self, day: f64, lat: f64, lon: f64) -> Option<(f64, f64)> {
        if self.timesteps.is_empty() || self.lats.is_empty() || self.lons.is_empty() {
            return None;
        }

        let lat_min = *self.lats.last().unwrap_or(&-90.0); // ERA5 lats may be descending
        let lat_max = *self.lats.first().unwrap_or(&90.0);
        let (lat_min, lat_max) = if lat_min < lat_max {
            (lat_min, lat_max)
        } else {
            (lat_max, lat_min)
        };
        let lon_min = *self.lons.first().unwrap_or(&0.0);
        let lon_max = *self.lons.last().unwrap_or(&360.0);

        if lat < lat_min || lat > lat_max || lon < lon_min || lon > lon_max {
            return None;
        }

        // Bracket in time
        let hi_idx = self
            .timesteps
            .iter()
            .position(|t| t.day_offset >= day)
            .unwrap_or(self.timesteps.len() - 1);
        let lo_idx = if hi_idx > 0 && self.timesteps[hi_idx].day_offset > day {
            hi_idx - 1
        } else {
            hi_idx
        };

        let lon_len = self.lons.len();
        let lo = &self.timesteps[lo_idx];
        let s_lo = bilinear(&self.lats, &self.lons, &lo.u, &lo.v, lon_len, lat, lon)?;

        if lo_idx == hi_idx {
            return Some(s_lo);
        }

        let hi = &self.timesteps[hi_idx];
        let s_hi = bilinear(&self.lats, &self.lons, &hi.u, &hi.v, lon_len, lat, lon)?;

        let dt = hi.day_offset - lo.day_offset;
        let t = if dt.abs() < 1e-9 {
            0.0
        } else {
            ((day - lo.day_offset) / dt).clamp(0.0, 1.0)
        };

        Some((
            s_lo.0 + (s_hi.0 - s_lo.0) * t,
            s_lo.1 + (s_hi.1 - s_lo.1) * t,
        ))
    }
}

// ---------------------------------------------------------------------------
// Bilinear interpolation (same pattern as oscar.rs)
// ---------------------------------------------------------------------------

fn bilinear(
    lats: &[f64],
    lons: &[f64],
    u: &[f32],
    v: &[f32],
    lon_len: usize,
    lat: f64,
    lon: f64,
) -> Option<(f64, f64)> {
    // ERA5 lats may be descending (90 to -90). Handle both orderings.
    let lats_ascending = lats.first().unwrap_or(&0.0) < lats.last().unwrap_or(&0.0);

    let (lat_lo_idx, lat_hi_idx, lat_frac) = if lats_ascending {
        bracket(lats, lat)?
    } else {
        // Descending: reverse the search
        let rev_idx = lats.iter().rposition(|&l| l >= lat)?;
        let lo = rev_idx.min(lats.len() - 2);
        let hi = lo + 1;
        let frac = if (lats[lo] - lats[hi]).abs() < 1e-9 {
            0.0
        } else {
            ((lats[lo] - lat) / (lats[lo] - lats[hi])).clamp(0.0, 1.0)
        };
        (lo, hi, frac)
    };

    let (lon_lo_idx, _, lon_frac) = bracket(lons, lon)?;
    let lon_hi_idx = if lon_lo_idx + 1 < lon_len {
        lon_lo_idx + 1
    } else {
        lon_lo_idx
    };

    let get = |lat_i: usize, lon_i: usize| -> (f64, f64) {
        let idx = lat_i * lon_len + lon_i;
        let uu = u.get(idx).copied().unwrap_or(0.0) as f64;
        let vv = v.get(idx).copied().unwrap_or(0.0) as f64;
        (uu, vv)
    };

    let c00 = get(lat_lo_idx, lon_lo_idx);
    let c10 = get(lat_hi_idx, lon_lo_idx);
    let c01 = get(lat_lo_idx, lon_hi_idx);
    let c11 = get(lat_hi_idx, lon_hi_idx);

    let u_interp = c00.0 * (1.0 - lat_frac) * (1.0 - lon_frac)
        + c10.0 * lat_frac * (1.0 - lon_frac)
        + c01.0 * (1.0 - lat_frac) * lon_frac
        + c11.0 * lat_frac * lon_frac;

    let v_interp = c00.1 * (1.0 - lat_frac) * (1.0 - lon_frac)
        + c10.1 * lat_frac * (1.0 - lon_frac)
        + c01.1 * (1.0 - lat_frac) * lon_frac
        + c11.1 * lat_frac * lon_frac;

    Some((u_interp, v_interp))
}

fn bracket(sorted: &[f64], value: f64) -> Option<(usize, usize, f64)> {
    if sorted.len() < 2 {
        return None;
    }
    let hi = sorted.iter().position(|&x| x >= value)?;
    let lo = if hi > 0 { hi - 1 } else { hi };
    let frac = if (sorted[hi] - sorted[lo]).abs() < 1e-9 {
        0.0
    } else {
        ((value - sorted[lo]) / (sorted[hi] - sorted[lo])).clamp(0.0, 1.0)
    };
    Some((lo, hi.min(sorted.len() - 1), frac))
}

// ---------------------------------------------------------------------------
// Cache loading
// ---------------------------------------------------------------------------

fn load_cache() -> Result<Era5WindCache, String> {
    let path = cache_path()?;
    eprintln!("ERA5 wind: looking for cache at {}", path.display());

    let raw = fs::read_to_string(&path).map_err(|e| {
        format!(
            "ERA5 wind cache not found at {}. Run: python knowledge/fetch_era5_wind.py — {}",
            path.display(),
            e
        )
    })?;

    eprintln!("ERA5 wind: read {} bytes from cache", raw.len());

    let cache: Era5WindCache = serde_json::from_str(&raw)
        .map_err(|e| format!("ERA5 wind cache parse failed: {e}"))?;

    if cache.version != CACHE_VERSION {
        return Err(format!(
            "ERA5 wind cache version mismatch (got {}, want {CACHE_VERSION})",
            cache.version,
        ));
    }

    eprintln!(
        "ERA5 wind: loaded cache ({} lat x {} lon x {} months)",
        cache.lats.len(),
        cache.lons.len(),
        cache.timesteps.len(),
    );

    Ok(cache)
}

fn cache_path() -> Result<PathBuf, String> {
    let base = std::env::current_dir().map_err(|e| format!("current dir: {e}"))?;
    let tauri_dir = if base.join("Cargo.toml").exists() {
        base.clone()
    } else {
        base.join("src-tauri")
    };
    Ok(tauri_dir.join(".cache").join("era5_wind_monthly.json"))
}
